name: coverage

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branch:
      - main

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v2

      - name: Run test with generating coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --out Xml

      - name: Upload to codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
